#!/usr/bin/env python3

import json
import pathlib
import argparse
import subprocess
from glob import glob

parser = argparse.ArgumentParser(description='Build NixOS images for installing on bare-metal machines')

parser.add_argument('--installer', type=str, default='raspberrypi', help='Installer name. See config.nix/installers')
parser.add_argument('--flash-to', type=pathlib.Path, default=None, help='Flash image to drive')
parser.add_argument('--progress', action='store_true', help='Show output from nix-build')
parser.add_argument('--no-nom', action='store_true', help='Don\'t show extended output from nom')

args = parser.parse_args()

print(f'Building image based on {args.installer}')

infoCmd = subprocess.run([
    'nix',
    'eval',
    '--json',
    f'.#nixosConfigurations.installer-{args.installer}.config',
    '--apply',
    'config: { inherit (config.nixpkgs) system; }',
],
    capture_output=True,
)

info = json.loads(infoCmd.stdout)
buildAttr = {
    'x86_64-linux': 'isoImage',
    'aarch64-linux': 'sdImage',
}[info['system']]

nomAvailable = subprocess.getstatusoutput('command -v nom')[0] == 0
buildCmd = subprocess.run([
    'nom' if args.progress and nomAvailable and not args.no_nom else 'nix',
    'build',
    f'.#nixosConfigurations.installer-{args.installer}.config.system.build.{buildAttr}',
],
    stdout=None if args.progress else subprocess.DEVNULL,
    stderr=None if args.progress else subprocess.DEVNULL,
)

if args.flash_to != None:
    images = glob('./result/iso/nixos-*.iso')
    if len(images) < 1:
        print('Could not determine ISO path; not flashing!')
    else:
        image = images[0]
        device = args.flash_to
        print(f'Flashing image {image} to {device}')
        buildCmd = subprocess.run([
            'sudo',
            'dd',
            'status=progress' if args.progress else '',
            f'if={image}',
            f'of={device}'
        ],
            stdout = None if args.progress else subprocess.DEVNULL,
        )

        if buildCmd.returncode == 0:
            print(f'Successfully flashed {image}')
            print(f'You may now remove {device}')
        else:
            print(f'Flash failed with dd error {buildCmd.returncode}')
else:
    print('Done')
