#!/usr/bin/env python3

import argparse
import subprocess
from glob import glob

parser = argparse.ArgumentParser(description='Build NixOS ISO for install on bare-metal machines')

parser.add_argument('--iso', default='bootstrap-iso.nix', help='Path to Nix module that builds an ISO')
parser.add_argument('--flash-to', default=None, help='Flash image to drive')
parser.add_argument('--progress', default=True, help='Show output from nix-build')

args = parser.parse_args()

print(f'Building ISO based on {args.iso}')

cmd = subprocess.run([
    'nix-build',
    '<nixpkgs/nixos>',
    '-A',
    'config.system.build.isoImage',
    '-I',
    f'nixos-config={args.iso}',
],
    capture_output=True,
    stdout = None if args.progress else subprocess.DEVNULL,
)

output = cmd.stdout

if args.flash_to != None:
    isos = glob('./result/iso/nixos-*.iso')
    if len(isos) < 1:
        print('Could not determine ISO path; not flashing!')
    else:
        iso = isos[0]
        device = args.flash_to
        print(f'Flashing ISO {iso} to {device}')
        cmd = subprocess.run([
            'sudo',
            'dd',
            'status=progress' if args.progress else '',
            f'if={iso}',
            f'of={device}'
        ],
            stdout = None if args.progress else subprocess.DEVNULL,
        )
        if cmd.returncode == 0:
            print(f'Successfully flashed {iso}')
            print(f'You may now remove {device}')
        else:
            print(f'Flash failed with dd error {cmd.returncode}')
